apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: wordpress
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www
        env:
          - name: WORDPRESS_DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-db-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_NAME
            value: wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-data
    
