---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  labels:
    app: wordpress
spec:
  storageClassName: aqua-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: wordpress
spec:
  storageClassName: aqua-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi