---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.persistence.wordpress.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.wordpress.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.persistence.mysql.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size }}