---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.persistence.wordpress.storageClass }}
  accessModes:
    - {{ .Values.persistence.wordpress.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.wordpress.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.persistence.mysql.storageClass }}
  accessModes:
    - {{ .Values.persistence.mysql.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size }}