apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
  type: {{ .Values.service.type }}
